name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  go-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
          cache: true
      - name: Run all tests
        run: go test -v ./... -tags=${{ matrix.release-tags }} -p=10 | tee test.log; exit ${PIPESTATUS[0]}
      - name: Pretty print tests running time
        # grep: filter out lines like "--- PASS: TestVCS (15.04s)"
        # sed: remove unnecessary characters
        # awk: re-format lines to "PASS: TestVCS (15.04s)"
        # sort: cut into columns by delimiter ' ' (single space) and sort by column 3 (test time in seconds) as numeric type in reverse order (largest comes first)
        # awk: accumulate sum by test time in seconds
        run: grep --color=never -e '--- PASS:' -e '--- FAIL:' test.log | sed 's/[:()]//g' | awk '{print $2,$3,$4}' | sort -t' ' -nk3 -r | awk '{sum += $3; print $1,$2,$3,sum"s"}'

